import { useState, useEffect } from 'react';
import { BrainCircuit, Sparkles, RotateCcw, ChevronLeft, ChevronRight, CheckCircle2, XCircle, Loader2 } from 'lucide-react';
import confetti from 'canvas-confetti';

export interface QuizQuestion {
  question: string;
  options: string[];
  correctIndex: number;
}

type QuizState = 'idle' | 'generating' | 'taking' | 'results';

const QUIZ_STORAGE_KEY = 'academy-quiz';

interface QuizStorage {
  quizState: QuizState;
  questions: QuizQuestion[];
  currentIndex: number;
  selectedAnswers: (number | null)[];
}

function loadQuizState(): QuizStorage | null {
  const saved = localStorage.getItem(QUIZ_STORAGE_KEY);
  if (saved) {
    try {
      return JSON.parse(saved);
    } catch (e) {
      console.error('Failed to parse quiz state', e);
    }
  }
  return null;
}

interface QuizPanelProps {
  documentContent: string;
}

const MAX_DOCUMENT_CHARS = 15000;

export function QuizPanel({ documentContent }: QuizPanelProps) {
  const saved = loadQuizState();
  // If page was reloaded while generating, reset to idle
  const [quizState, setQuizState] = useState<QuizState>(saved?.quizState === 'generating' ? 'idle' : (saved?.quizState ?? 'idle'));
  const [questions, setQuestions] = useState<QuizQuestion[]>(saved?.questions ?? []);
  const [currentIndex, setCurrentIndex] = useState(saved?.currentIndex ?? 0);
  const [selectedAnswers, setSelectedAnswers] = useState<(number | null)[]>(saved?.selectedAnswers ?? []);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const data: QuizStorage = { quizState, questions, currentIndex, selectedAnswers };
    localStorage.setItem(QUIZ_STORAGE_KEY, JSON.stringify(data));
  }, [quizState, questions, currentIndex, selectedAnswers]);

  const handleGenerateQuiz = async () => {
    if (documentContent.length > MAX_DOCUMENT_CHARS) {
      setError(`Document exceeds ${MAX_DOCUMENT_CHARS.toLocaleString()} characters. Please upload a smaller file.`);
      setQuizState('idle');
      return;
    }

    setQuizState('generating');
    setError(null);
    try {
      const res = await fetch('/api/generate-quiz', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ content: documentContent }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Failed to generate quiz');
      setQuestions(data.questions);
      setSelectedAnswers(new Array(data.questions.length).fill(null));
      setCurrentIndex(0);
      setQuizState('taking');
    } catch (e: any) {
      setError(e.message);
      setQuizState('idle');
    }
  };

  const handleSelectAnswer = (optionIndex: number) => {
    setSelectedAnswers(prev => {
      const updated = [...prev];
      updated[currentIndex] = optionIndex;
      return updated;
    });
  };

  const handleSubmit = () => {
    setQuizState('results');
    // Fire confetti
    confetti({
      particleCount: 150,
      spread: 80,
      origin: { y: 0.6, x: 0.5 },
    });
    setTimeout(() => {
      confetti({
        particleCount: 80,
        spread: 100,
        origin: { y: 0.5, x: 0.3 },
      });
    }, 300);
    setTimeout(() => {
      confetti({
        particleCount: 80,
        spread: 100,
        origin: { y: 0.5, x: 0.7 },
      });
    }, 600);
  };

  const handleRetake = () => {
    setQuizState('idle');
    setQuestions([]);
    setSelectedAnswers([]);
    setCurrentIndex(0);
  };

  const correctCount = questions.reduce(
    (acc, q, i) => acc + (selectedAnswers[i] === q.correctIndex ? 1 : 0),
    0
  );
  const incorrectCount = questions.length - correctCount;

  // IDLE STATE - Start quiz
  if (quizState === 'idle') {
    return (
      <div className="p-md flex flex-col items-center justify-center text-center gap-md h-full">
        <div className="w-16 h-16 rounded-full bg-tertiary/10 flex items-center justify-center">
          <BrainCircuit className="w-8 h-8 text-tertiary" />
        </div>
        <h4 className="text-[16px] font-headline-sm font-semibold text-on-surface">Knowledge Quiz</h4>
        <p className="text-[14px] text-on-surface-variant leading-relaxed max-w-[240px]">
          Test your understanding of the documentation with a 5-question multiple choice quiz generated by AI.
        </p>
        {error && (
          <p className="text-[12px] text-error bg-error/10 px-3 py-1.5 rounded">{error}</p>
        )}
        <button
          onClick={handleGenerateQuiz}
          className="mt-sm flex items-center gap-2 bg-tertiary text-on-tertiary px-5 py-2.5 rounded-lg font-semibold text-[14px] hover:bg-tertiary/90 transition-colors shadow-md"
        >
          <Sparkles className="w-4 h-4" />
          Generate Quiz
        </button>
      </div>
    );
  }

  // GENERATING STATE - Loading animation
  if (quizState === 'generating') {
    return (
      <div className="p-md flex flex-col items-center justify-center text-center gap-md h-full">
        <div className="relative w-20 h-20">
          <div className="absolute inset-0 rounded-full border-4 border-tertiary/20" />
          <div className="absolute inset-0 rounded-full border-4 border-transparent border-t-tertiary animate-spin" />
          <div className="absolute inset-2 rounded-full border-4 border-transparent border-b-primary animate-spin [animation-direction:reverse] [animation-duration:1.5s]" />
          <div className="absolute inset-0 flex items-center justify-center">
            <BrainCircuit className="w-7 h-7 text-tertiary animate-pulse" />
          </div>
        </div>
        <h4 className="text-[16px] font-headline-sm font-semibold text-on-surface">Generating Quiz...</h4>
        <p className="text-[13px] text-on-surface-variant leading-relaxed max-w-[220px]">
          AI is crafting questions based on the documentation
        </p>
        <div className="flex gap-1 mt-sm">
          <span className="w-2 h-2 rounded-full bg-tertiary animate-bounce [animation-delay:0ms]" />
          <span className="w-2 h-2 rounded-full bg-tertiary animate-bounce [animation-delay:150ms]" />
          <span className="w-2 h-2 rounded-full bg-tertiary animate-bounce [animation-delay:300ms]" />
        </div>
      </div>
    );
  }

  // RESULTS STATE
  if (quizState === 'results') {
    return (
      <div className="flex flex-col h-full">
        {/* Header */}
        <div className="p-md border-b border-outline-variant bg-surface-container-lowest">
          <h4 className="text-[16px] font-headline-sm font-semibold text-on-surface text-center">Quiz Results</h4>
        </div>

        <div className="flex-1 overflow-y-auto p-md flex flex-col gap-md scrollbar-hide">
          {/* Score summary */}
          <div className="flex items-center justify-center gap-lg py-md">
            <div className="flex flex-col items-center gap-xs">
              <div className="w-14 h-14 rounded-full bg-green-500/10 flex items-center justify-center border-2 border-green-500/30">
                <span className="text-[22px] font-bold text-green-600 dark:text-green-400">{correctCount}</span>
              </div>
              <span className="text-[12px] text-on-surface-variant font-medium">Correct</span>
            </div>
            <div className="text-[24px] text-on-surface-variant font-light">/</div>
            <div className="flex flex-col items-center gap-xs">
              <div className="w-14 h-14 rounded-full bg-red-500/10 flex items-center justify-center border-2 border-red-500/30">
                <span className="text-[22px] font-bold text-red-600 dark:text-red-400">{incorrectCount}</span>
              </div>
              <span className="text-[12px] text-on-surface-variant font-medium">Incorrect</span>
            </div>
          </div>

          {/* Score bar */}
          <div className="w-full bg-surface-variant rounded-full h-2.5 overflow-hidden">
            <div
              className="h-full bg-green-500 rounded-full transition-all duration-500"
              style={{ width: `${(correctCount / questions.length) * 100}%` }}
            />
          </div>
          <p className="text-center text-[13px] text-on-surface-variant">
            You scored {correctCount} out of {questions.length} ({Math.round((correctCount / questions.length) * 100)}%)
          </p>

          {/* Review questions */}
          <div className="flex flex-col gap-sm mt-sm">
            {questions.map((q, idx) => {
              const userAnswer = selectedAnswers[idx];
              const isCorrect = userAnswer === q.correctIndex;
              return (
                <div
                  key={idx}
                  className={`rounded-lg border p-sm ${
                    isCorrect
                      ? 'border-green-500/30 bg-green-500/5'
                      : 'border-red-500/30 bg-red-500/5'
                  }`}
                >
                  <div className="flex items-start gap-xs mb-xs">
                    {isCorrect ? (
                      <CheckCircle2 className="w-4 h-4 text-green-500 shrink-0 mt-0.5" />
                    ) : (
                      <XCircle className="w-4 h-4 text-red-500 shrink-0 mt-0.5" />
                    )}
                    <p className="text-[13px] font-medium text-on-surface leading-tight">{q.question}</p>
                  </div>
                  {!isCorrect && (
                    <div className="ml-6 text-[12px]">
                      <p className="text-red-600 dark:text-red-400 line-through">
                        Your answer: {userAnswer !== null ? q.options[userAnswer] : 'No answer'}
                      </p>
                      <p className="text-green-600 dark:text-green-400 font-medium">
                        Correct: {q.options[q.correctIndex]}
                      </p>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>

        {/* Retake button */}
        <div className="p-md border-t border-outline-variant bg-surface-container-lowest shrink-0">
          <button
            onClick={handleRetake}
            className="w-full flex items-center justify-center gap-2 bg-tertiary text-on-tertiary py-2.5 rounded-lg font-semibold text-[14px] hover:bg-tertiary/90 transition-colors"
          >
            <RotateCcw className="w-4 h-4" />
            Retake Quiz
          </button>
        </div>
      </div>
    );
  }

  // TAKING QUIZ STATE
  const currentQuestion = questions[currentIndex];
  const isFirstQuestion = currentIndex === 0;
  const isLastQuestion = currentIndex === questions.length - 1;
  const hasAnswered = selectedAnswers[currentIndex] !== null;
  const allAnswered = selectedAnswers.every(a => a !== null);

  return (
    <div className="flex flex-col h-full">
      {/* Progress header */}
      <div className="p-md border-b border-outline-variant bg-surface-container-lowest shrink-0">
        <div className="flex items-center justify-between mb-xs">
          <span className="text-[12px] text-on-surface-variant font-medium">
            Question {currentIndex + 1} of {questions.length}
          </span>
          <span className="text-[12px] text-tertiary font-semibold">
            {selectedAnswers.filter(a => a !== null).length}/{questions.length} answered
          </span>
        </div>
        <div className="w-full bg-surface-variant rounded-full h-1.5 overflow-hidden">
          <div
            className="h-full bg-tertiary rounded-full transition-all duration-300"
            style={{ width: `${((currentIndex + 1) / questions.length) * 100}%` }}
          />
        </div>
      </div>

      {/* Question content */}
      <div className="flex-1 overflow-y-auto p-md flex flex-col gap-md scrollbar-hide">
        <p className="text-[14px] font-semibold text-on-surface leading-relaxed">
          {currentQuestion.question}
        </p>

        <div className="flex flex-col gap-xs">
          {currentQuestion.options.map((option, optIdx) => {
            const isSelected = selectedAnswers[currentIndex] === optIdx;
            return (
              <button
                key={optIdx}
                onClick={() => handleSelectAnswer(optIdx)}
                className={`w-full text-left px-sm py-sm rounded-lg border text-[13px] transition-all ${
                  isSelected
                    ? 'border-tertiary bg-tertiary/10 text-on-surface font-medium ring-1 ring-tertiary/50'
                    : 'border-outline-variant bg-surface-container hover:bg-surface-container-highest hover:border-outline text-on-surface-variant'
                }`}
              >
                <span className="flex items-center gap-sm">
                  <span className={`w-5 h-5 rounded-full border-2 flex items-center justify-center shrink-0 ${
                    isSelected ? 'border-tertiary bg-tertiary' : 'border-outline-variant'
                  }`}>
                    {isSelected && <span className="w-2 h-2 rounded-full bg-on-tertiary" />}
                  </span>
                  {option}
                </span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Navigation buttons */}
      <div className="p-md border-t border-outline-variant bg-surface-container-lowest shrink-0 flex gap-sm">
        {!isFirstQuestion && (
          <button
            onClick={() => setCurrentIndex(i => i - 1)}
            className="flex-1 flex items-center justify-center gap-1 border border-outline-variant text-on-surface py-2 rounded-lg font-medium text-[13px] hover:bg-surface-variant/30 transition-colors"
          >
            <ChevronLeft className="w-4 h-4" />
            Back
          </button>
        )}
        {isLastQuestion ? (
          <button
            onClick={handleSubmit}
            disabled={!allAnswered}
            className="flex-1 flex items-center justify-center gap-1 bg-tertiary text-on-tertiary py-2 rounded-lg font-semibold text-[13px] hover:bg-tertiary/90 transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
          >
            Submit
            <CheckCircle2 className="w-4 h-4" />
          </button>
        ) : (
          <button
            onClick={() => setCurrentIndex(i => i + 1)}
            className="flex-1 flex items-center justify-center gap-1 bg-tertiary text-on-tertiary py-2 rounded-lg font-semibold text-[13px] hover:bg-tertiary/90 transition-colors"
          >
            Next
            <ChevronRight className="w-4 h-4" />
          </button>
        )}
      </div>
    </div>
  );
}
